### ISSUE TITLE
[Bug]: Error attaching animation in HCT2010

### ISSUE THREAD

**Issue by WasmachenDennSachenSo** [SARDONYX-sard/serde-hkx#11]
### Version

0.1.2

### Reproducible errors

I converted all of the Skyrim SE assets inside of Skyrim_Animations.bsa from 64Bit to 32Bit and opened the 32Bit version of the Troll "skeleton.hkx" inside of the Havok Content Tools 2010.2.0.1 32Bit. This worked fine and everything seems to be loaded properly. However, I can't add an animation (h2hattacklefta.hkx, also 32Bit of course) to the skeleton, it throws the attached error.

### Expected behavior

It should just open, duh. I guess the log will be pretty useless, since you don't have the source of the HCT.

### Relevant log output

```Shell
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at PreviewPlugin.PreviewAsset.makeRewindPoint(PreviewAsset* , hkVtableClassRegistry* )
   at PreviewPlugin.hctPreviewControl.addAssetsFromFile(ArrayList files, AddAssetType t)
   at PreviewPlugin.hctPreviewControl.setContentsFromFile(String path, Boolean dragIn, Int32 x, Int32 y, Boolean prompt)
   at Havok.Tool.Plugins.SetContentsFromFile(String path, Boolean dragIn, Int32 x, Int32 y, Boolean prompt)
   at Havok.Tool.ToolUI.addHKXToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
ToolStandAlone
    Assembly Version: 2010.2.0.1
    Win32 Version: 2010.2.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Havok32/HavokContentTools/ToolStandAlone.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Havok.Tool.UI
    Assembly Version: 2010.2.0.1
    Win32 Version: 2010.2.0.1
    CodeBase: file:///C:/Windows/assembly/GAC_32/Havok.Tool.UI/2010.2.0.1__b7c2834b000f387a/Havok.Tool.UI.dll
----------------------------------------
Havok.Tool.Interfaces
    Assembly Version: 2010.2.0.1
    Win32 Version: 
    CodeBase: file:///C:/Windows/assembly/GAC_32/Havok.Tool.Interfaces/2010.2.0.1__b7c2834b000f387a/Havok.Tool.Interfaces.dll
----------------------------------------
msvcm90
    Assembly Version: 9.0.30729.9635
    Win32 Version: 9.00.30729.9635
    CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9635_none_508ff82ebcbafee0/msvcm90.dll
----------------------------------------
Havok.Graphics
    Assembly Version: 2010.2.0.1
    Win32 Version: 
    CodeBase: file:///C:/Windows/assembly/GAC_32/Havok.Graphics/2010.2.0.1__3a48fc937fbc76fe/Havok.Graphics.dll
----------------------------------------
hctPreviewPlugin
    Assembly Version: 2010.2.0.1
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Havok32/HavokContentTools/tools/hctPreviewPlugin.dll
----------------------------------------
Havok.Graphics.Bridge
    Assembly Version: 2010.2.0.1
    Win32 Version: 
    CodeBase: file:///C:/Windows/assembly/GAC_32/Havok.Graphics.Bridge/2010.2.0.1__b7c2834b000f387a/Havok.Graphics.Bridge.dll
----------------------------------------
hctTweakerPlugin
    Assembly Version: 2010.2.0.1
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Havok32/HavokContentTools/tools/hctTweakerPlugin.dll
----------------------------------------
HavokDynamicAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/Havok32/HavokContentTools/tools/hctTweakerPlugin.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by WasmachenDennSachenSo** [comment]
https://github.com/user-attachments/assets/179fd9de-b14a-4de6-80ab-2fa76b903936

This is the expected behavior with HCT2010.2.0.1 64Bit and all 64Bit assets.

**Comment by SARDONYX-sard** [comment]
0.1.2 is buggy, try [0.2.0](https://github.com/SARDONYX-sard/serde-hkx/releases/tag/0.2.0)

bug: https://github.com/SARDONYX-sard/serde-hkx/issues/9

**Comment by WasmachenDennSachenSo** [comment]
Yeah, version 2.0 fixed this. Thank you :)

**Comment by SARDONYX-sard** [comment]
Congratulations! Yay!
